### ISSUE TITLE
Нужно сделать array шаблонным

### ISSUE THREAD

**Issue by Danoxz** [Ilukard/Laba1#1]
Во 2 практике, нужно использовать самописный array, и хранить там разные типы данных, не только int:
https://github.com/Ilukard/Laba1/blob/8d9a3f32ad693013bdb1d3b3f57cbc216575b116/arr.cpp#L7
Должно быть
```cpp
template <typename T>
struct array {
   int vmest; 
   int dlina;
   T *data;
...
```

**Comment by Ilukard** [comment]
Готово Гоооол
